"""/stock-report build pipeline.

ARCHITECTURE
------------
Python validates inputs, preps deterministic data (XBRL series, memo header, sector
detection, FACT-claim records, chart specs), runs glossary auto-injection on Claude's
drafts, and assembles the final HTML. Python does NOT write prose. Claude writes each
section's prose into `_report_drafts/section_NN_<slug>.md` (per the per-section writing
prompts in SKILL.md). The drafts are persisted across runs.

USAGE
-----
  py build_report.py TICKER --prep                # validate + write report_data.json
  py build_report.py TICKER --assemble            # read drafts + emit final HTML
  py build_report.py TICKER                       # both phases
  py build_report.py TICKER --rebuild             # clear all drafts, then both phases
  py build_report.py TICKER --rebuild-section N   # clear one draft, then both phases
  py build_report.py TICKER --status              # show which section drafts exist

OUTPUTS
-------
  {BASE}/_report_drafts/report_data.json          # deterministic prep output
  {BASE}/_report_drafts/sector_detected.txt       # GICS sector + reason
  {BASE}/_report_drafts/section_NN_<slug>.md      # per-section drafts (Claude writes)
  {BASE}/_report_drafts/glossary_company.json     # per-company glossary (Claude writes)
  {BASE}/{TICKER}_full_report.html                # final assembled report

Stdlib only.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import html as _html
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
import svg_charts  # noqa: E402

try:
    import inject_glossary  # noqa: E402
    HAS_GLOSSARY_INJECT = True
except ImportError:
    HAS_GLOSSARY_INJECT = False


# ---------- the 14 sections (operating-manual anatomy) ----------
# (number, slug, title, kind)
# Sections 1-11 require a Claude draft. 12-14 are auto-generated by Python.
# Anatomy follows the research document at
#   assets/compass_artifact_wf-73c18398-84f7-402f-af5c-5ab84e12a418_text_markdown.md
# Sections 1-10 are the operating-manual anatomy from Part III of that document;
# Section 11 is the user-requested recommendation block at the bottom.
SECTIONS = [
    (1,  "lede",                  "The lede",                              "claude"),
    (2,  "unit_economics",        "Unit economics",                        "claude"),
    (3,  "product",               "The product, judged by its users",      "claude"),
    (4,  "customer_and_demand",   "The customer and demand",               "claude"),
    (5,  "industry",              "The industry, through this company",    "claude"),
    (6,  "moat",                  "Moat",                                  "claude"),
    (7,  "management",            "Management and capital allocation",     "claude"),
    (8,  "financial_history",     "Financial history",                     "claude"),
    (9,  "premortem",             "Pre-mortem",                            "claude"),
    (10, "valuation",             "Valuation as expectations",             "claude"),
    (11, "disconfirmation",       "What would change my mind",             "claude"),
    (12, "recommendation",        "Recommendation",                        "claude"),
    (13, "reliability",           "Reliability disclosure",                "auto"),
    (14, "glossary",              "Glossary",                              "auto"),
    (15, "sources",               "Source trail",                          "auto"),
]


REQUIRED_FILES = [
    "{TICKER}_research_memo.md",
    "raw/verification_a.md",
]

OPTIONAL_FILES = [
    "steps/verification_b.md",
    "steps/verification_c.md",
    "raw/10k.md",
    "raw/10q.md",
    "raw/proxy.md",
    "raw/competitors.md",
    "raw/insider.md",
    "raw/transcripts.md",
    "raw/customer_perspective.md",
    "raw/xbrl_summary.txt",
    "raw/cc_catches_against_codex.md",
    "steps/step3_business_model.md",
    "steps/step4_industry.md",
    "steps/step4b_customer_perspective.md",
    "steps/step5_moat_current.md",
    "steps/step6_moat_durability.md",
    "steps/step7_accounting.md",
    "steps/step8_management.md",
    "steps/step9_valuation.md",
    "steps/step10_counter_attack.md",
    "steps/step10_codex_attack.md",
    "steps/step11_final_memo.md",
    "bugs_encountered.md",
    "bugs_encountered_codex.md",
]


# ---------- helpers ----------

def read_text(p: Path) -> str:
    if not p.exists():
        return ""
    try:
        return p.read_text(encoding="utf-8")
    except Exception as e:
        return f"[ERROR reading {p}: {e}]"


def validate(base: Path, ticker: str) -> list[str]:
    missing = []
    for rel in REQUIRED_FILES:
        p = base / rel.replace("{TICKER}", ticker)
        if not p.exists():
            missing.append(str(p))
    return missing


# ---------- XBRL ----------

def parse_xbrl_summary(path: Path) -> dict:
    """Parse `xbrl_summary.txt` into {label: [(end_date, value, unit)]}."""
    if not path.exists():
        return {}
    out: dict[str, list[tuple[str, float, str]]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 4:
            continue
        label_concept = parts[0]
        label = label_concept.split("(", 1)[0].strip()
        end = parts[1]
        try:
            val = float(parts[2])
        except (ValueError, TypeError):
            continue
        unit = parts[3] if len(parts) > 3 else ""
        out.setdefault(label, []).append((end, val, unit))
    for k in out:
        out[k] = sorted(out[k], key=lambda x: x[0])
    return out


# ---------- memo header parsing ----------

def parse_memo_header(memo_md: str) -> dict:
    """Extract decision, company, current price (from 'Stock price anchored to' line),
    intrinsic estimate, and key insight body."""
    info = {
        "decision": "",
        "current_price": "",
        "intrinsic": "",
        "key_insight": "",
        "thesis_one_liner": "",
        "company": "",
        "memo_date": "",
    }

    h1 = re.search(r"^#\s+(.+)$", memo_md, flags=re.MULTILINE)
    if h1:
        info["company"] = h1.group(1).strip()
        date_m = re.search(r"(\d{4}-\d{2}-\d{2})", h1.group(1))
        if date_m:
            info["memo_date"] = date_m.group(1)

    # Canonical "Stock price anchored to: $X" line — must win over any later $NNN
    # because Section 1 typically also contains trigger / watch prices that would
    # otherwise be picked up as the current price.
    for line in memo_md.splitlines()[:60]:
        if "stock price anchored" in line.lower():
            p_m = re.search(r"\$([0-9]+(?:\.[0-9]{1,2})?)", line)
            if p_m:
                info["current_price"] = "$" + p_m.group(1)
                break

    decision_section = _section_body(memo_md, r"Section\s+1\b[^#\n]*|DECISION")
    if decision_section:
        d_m = re.search(r"\b(BUY|WATCHLIST|PASS|REJECT|WATCH)\b", decision_section, re.IGNORECASE)
        if d_m:
            info["decision"] = d_m.group(1).upper()
        if not info["current_price"]:
            p_m = re.search(r"\$([0-9]+(?:\.[0-9]{1,2})?)", decision_section)
            if p_m:
                info["current_price"] = "$" + p_m.group(1)
        first_para = decision_section.strip().split("\n\n", 1)[0]
        info["thesis_one_liner"] = first_para

    if not info["decision"]:
        d_m = re.search(
            r"\b(BUY|WATCHLIST|PASS|REJECT)\b",
            "\n".join(memo_md.splitlines()[:80]),
            re.IGNORECASE,
        )
        if d_m:
            info["decision"] = d_m.group(1).upper()

    ki = _section_body(memo_md, r"Section\s+3\b[^#\n]*|KEY\s+INSIGHT")
    if ki:
        info["key_insight"] = ki.strip()

    intrinsic_m = re.search(
        r"intrinsic[^$]*\$([0-9]+(?:\.[0-9]{1,2})?)",
        memo_md,
        re.IGNORECASE,
    )
    if intrinsic_m:
        info["intrinsic"] = "$" + intrinsic_m.group(1)

    return info


def _section_body(md: str, header_pattern: str) -> str:
    """Find a section by partial header match, return its body up to next ##."""
    for m in re.finditer(r"(?m)^##\s+(.+)$", md):
        if re.search(header_pattern, m.group(1), re.IGNORECASE):
            start = m.end()
            next_m = re.search(r"(?m)^##\s+", md[start:])
            end = start + next_m.start() if next_m else len(md)
            return md[start:end].strip()
    return ""


# ---------- GICS classification (authoritative file only) ----------
# The keyword-fingerprint detector that used to live here was deleted because it
# routinely misclassified service companies that deliver via software (Paychex was
# classified as Information Technology when the correct sector is Industrials).
# The replacement is the universal "don't guess - look up" rule: Claude resolves
# the GICS classification at run time via WebFetch on the company's Wikipedia page
# or IR page, falling back to AskUserQuestion if web lookup fails. That logic lives
# in SKILL.md (Step 0 of the orchestration). Python here is a dumb reader of
# raw/gics.txt; if the file is missing, we exit with a clear error pointing back
# to SKILL.md.

def _load_gics(base: Path) -> dict | None:
    """Read GICS classification from `raw/gics.txt` if present.

    Expected format (case-insensitive keys; whitespace-tolerant):
        Sector: Industrials
        Industry: Professional Services
        Sub-Industry: Human Resource & Employment Services

    Sector is required; Industry and Sub-Industry are optional.
    Returns None if the file is missing.
    """
    p = base / "raw" / "gics.txt"
    if not p.exists():
        return None
    out: dict[str, str] = {}
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip().lower().replace(" ", "_").replace("-", "_")
        value = value.strip()
        if not value:
            continue
        if key in {"sector", "industry", "sub_industry", "subindustry", "industry_group"}:
            # Normalize sub-industry key
            if key == "subindustry":
                key = "sub_industry"
            out[key] = value
    if "sector" not in out:
        return None
    return out


def _slug(name: str) -> str:
    """Normalize a GICS name into the file-slug convention used by the primer prompts.
    'Real Estate Management & Development' -> 'Real_Estate_Management_and_Development'."""
    s = name.replace("&", "and")
    s = re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_")
    return s


def resolve_classification(base: Path) -> dict | None:
    """Read GICS classification from raw/gics.txt (the only allowed source).

    Returns a dict with sector / industry / sub_industry / source / reason fields,
    or None if raw/gics.txt is missing. The caller is responsible for handling the
    None case - typically by exiting with a clear instruction pointing the reader to
    SKILL.md's Step 0 (look up GICS via WebFetch on Wikipedia or company IR page;
    AskUserQuestion as fallback). The skill never guesses GICS classification."""
    gics = _load_gics(base)
    if gics is None:
        return None
    return {
        "sector": gics.get("sector", ""),
        "industry": gics.get("industry", ""),
        "sub_industry": gics.get("sub_industry", ""),
        "source": "raw/gics.txt",
        "reason": "Loaded from raw/gics.txt (authoritative).",
    }


def primer_paths(classification: dict) -> dict:
    """Compute expected primer file paths and check presence.
    Returns a dict with sector / industry primer paths, statuses, and the prompt-file
    path the user can run if a primer is missing."""
    skill_assets = SKILL_DIR / "assets"
    out: dict = {"sector": {}, "industry": {}}

    sec = classification.get("sector", "")
    if sec and sec not in {"UNKNOWN", "AMBIGUOUS", ""}:
        sec_slug = _slug(sec)
        sec_primer = skill_assets / "sectors" / f"{sec_slug}_primer.md"
        sec_prompt = skill_assets / "sectors" / "_research_prompts" / f"{sec_slug}_primer_prompt.md"
        out["sector"] = {
            "name": sec,
            "primer_path": str(sec_primer),
            "primer_status": "present" if sec_primer.exists() else "missing",
            "research_prompt_path": str(sec_prompt) if sec_prompt.exists() else None,
        }
    else:
        out["sector"] = {
            "name": sec, "primer_path": "", "primer_status": "no_sector_classification",
            "research_prompt_path": None,
        }

    ind = classification.get("industry", "")
    if ind:
        ind_slug = _slug(ind)
        ind_primer = skill_assets / "industries" / f"{ind_slug}_primer.md"
        ind_prompt = skill_assets / "industries" / "_research_prompts" / f"{ind_slug}_primer_prompt.md"
        out["industry"] = {
            "name": ind,
            "primer_path": str(ind_primer),
            "primer_status": "present" if ind_primer.exists() else "missing",
            "research_prompt_path": str(ind_prompt) if ind_prompt.exists() else None,
        }
    else:
        out["industry"] = {
            "name": "", "primer_path": "", "primer_status": "no_industry_classification",
            "research_prompt_path": None,
        }

    return out


# ---------- claim extraction ----------

CLAIM_RE = re.compile(
    r"\[(FACT|INTERPRETATION|HUMAN-VERIFY)\s*\|\s*([^\|\]]+?)\s*(?:\|\s*([^\]]+?))?\]"
)


def extract_claims(files: dict) -> list[dict]:
    """Scan step files for `[FACT|source|confidence]` style tags. Returns structured
    records. Claude can reference these by id when writing prose; the reader never
    sees the raw [FACT|...] chips in the body."""
    records = []
    cid = 0
    for filename, content in files.items():
        if not filename.startswith("steps/"):
            continue
        for line_num, line in enumerate(content.splitlines(), 1):
            for m in CLAIM_RE.finditer(line):
                cid += 1
                records.append({
                    "id": f"c{cid:04d}",
                    "kind": m.group(1),
                    "source": (m.group(2) or "").strip(),
                    "confidence": (m.group(3) or "").strip(),
                    "file": filename,
                    "line": line_num,
                })
    return records


# ---------- chart specs ----------

def build_chart_specs(xbrl: dict) -> list[dict]:
    """Return list of chart specs for the assembler to render. Each spec:
        {kind, id, title, data, ylabel, caption_slot_section}
    The caption_slot_section tells which section's draft is allowed to write the
    one-line takeaway caption; Claude inserts the caption text inline in the draft
    via a `<!-- chart-caption: chart_id="...", text="..." -->` marker."""
    specs = []
    if not xbrl:
        return specs

    rev = xbrl.get("Revenue") or xbrl.get("Revenues")
    if rev:
        specs.append({
            "kind": "line",
            "id": "revenue_5y",
            "title": "Revenue, 5-year",
            "labels": [d[:4] for d, _, _ in rev[-5:]],
            "series": {"Revenue": [v for _, v, _ in rev[-5:]]},
            "ylabel": "USD",
            "caption_slot_section": 4,
        })

    op = xbrl.get("OperatingIncome")
    if rev and op:
        rev_by_year = {d[:4]: v for d, v, _ in rev}
        labels, margins = [], []
        for d, v, _ in op[-5:]:
            yr = d[:4]
            r = rev_by_year.get(yr)
            if r:
                labels.append(yr)
                margins.append(v / r * 100)
        if labels:
            specs.append({
                "kind": "line",
                "id": "op_margin_5y",
                "title": "Operating margin, 5-year (%)",
                "labels": labels,
                "series": {"Op margin %": margins},
                "ylabel": "%",
                "caption_slot_section": 4,
            })

    ocf = xbrl.get("OperatingCashFlow")
    if ocf:
        specs.append({
            "kind": "bar",
            "id": "ocf_5y",
            "title": "Operating cash flow, 5-year",
            "labels": [d[:4] for d, _, _ in ocf[-5:]],
            "values": [v for _, v, _ in ocf[-5:]],
            "ylabel": "USD",
            "caption_slot_section": 4,
        })

    sh = xbrl.get("SharesOutstanding")
    if sh:
        specs.append({
            "kind": "line",
            "id": "shares_5y",
            "title": "Shares outstanding, 5-year",
            "labels": [d[:4] for d, _, _ in sh[-5:]],
            "series": {"Shares": [v for _, v, _ in sh[-5:]]},
            "ylabel": "shares",
            "caption_slot_section": 4,
        })

    debt = xbrl.get("LongTermDebt")
    if debt:
        specs.append({
            "kind": "bar",
            "id": "debt_5y",
            "title": "Long-term debt, 5-year",
            "labels": [d[:4] for d, _, _ in debt[-5:]],
            "values": [v for _, v, _ in debt[-5:]],
            "ylabel": "USD",
            "caption_slot_section": 4,
        })

    return specs


def render_chart(spec: dict) -> str:
    """Render a chart spec into SVG via svg_charts."""
    if spec["kind"] == "line":
        return svg_charts.line_chart(
            spec["title"], spec["labels"], spec["series"], ylabel=spec.get("ylabel", "")
        )
    if spec["kind"] == "bar":
        return svg_charts.bar_chart(
            spec["title"], spec["labels"], spec["values"], ylabel=spec.get("ylabel", "")
        )
    return f'<!-- chart kind {spec["kind"]} not yet supported -->'


# ---------- draft management ----------

def drafts_dir(base: Path) -> Path:
    return base / "_report_drafts"


def section_filename(num: int, slug: str) -> str:
    return f"section_{num:02d}_{slug}.md"


def section_path(base: Path, num: int, slug: str) -> Path:
    return drafts_dir(base) / section_filename(num, slug)


def clear_drafts(base: Path, only_section: int | None = None) -> list[str]:
    """Delete section drafts. Returns list of deleted filenames."""
    deleted = []
    for num, slug, _, kind in SECTIONS:
        if kind != "claude":
            continue
        if only_section is not None and num != only_section:
            continue
        p = section_path(base, num, slug)
        if p.exists():
            p.unlink()
            deleted.append(p.name)
    return deleted


def check_drafts(base: Path) -> list[dict]:
    """Return per-section status."""
    out = []
    for num, slug, title, kind in SECTIONS:
        if kind != "claude":
            out.append({"num": num, "slug": slug, "title": title, "status": "auto"})
            continue
        p = section_path(base, num, slug)
        if p.exists():
            text = p.read_text(encoding="utf-8")
            out.append({
                "num": num, "slug": slug, "title": title,
                "status": "drafted",
                "words": len(text.split()),
                "path": str(p),
            })
        else:
            out.append({
                "num": num, "slug": slug, "title": title,
                "status": "missing",
                "path": str(p),
            })
    return out


# ---------- prep phase ----------

def prep(base: Path, ticker: str) -> dict:
    """Validate inputs, parse data, detect sector, write report_data.json. Returns
    the data dict in addition to writing it to disk."""
    missing = validate(base, ticker)
    if missing:
        print("ERROR: required input files missing:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        print(
            f"\n/stock-research {ticker} must complete first (memo + verification_a).",
            file=sys.stderr,
        )
        sys.exit(1)

    files: dict[str, str] = {}
    for rel in REQUIRED_FILES + OPTIONAL_FILES:
        key = rel.replace("{TICKER}", ticker)
        files[key] = read_text(base / key)

    xbrl = parse_xbrl_summary(base / "raw" / "xbrl_summary.txt")
    memo_info = parse_memo_header(files.get(f"{ticker}_research_memo.md", ""))

    classification = resolve_classification(base)
    if classification is None:
        print("ERROR: raw/gics.txt is missing and the skill never guesses GICS classification.",
              file=sys.stderr)
        print("", file=sys.stderr)
        print("To produce raw/gics.txt:", file=sys.stderr)
        print("  - WebFetch the company's Wikipedia page; the GICS sector and industry are", file=sys.stderr)
        print("    typically in the infobox.", file=sys.stderr)
        print("  - If Wikipedia lacks the info, try the company's investor-relations page.", file=sys.stderr)
        print("  - If still unresolved, ask the user.", file=sys.stderr)
        print("", file=sys.stderr)
        print("Write the result at " + str(base / "raw" / "gics.txt") + " in the format:", file=sys.stderr)
        print("    Sector: <GICS sector>", file=sys.stderr)
        print("    Industry: <GICS industry>", file=sys.stderr)
        print("    Sub-Industry: <GICS sub-industry>", file=sys.stderr)
        print("", file=sys.stderr)
        print("Then re-run /stock-report. See SKILL.md Step 0 for the full orchestration.",
              file=sys.stderr)
        sys.exit(1)
    primers = primer_paths(classification)

    chart_specs = build_chart_specs(xbrl)
    claims = extract_claims(files)

    data = {
        "_meta": {
            "ticker": ticker,
            "build_date": _dt.date.today().isoformat(),
            "skill_dir": str(SKILL_DIR),
            "research_base": str(base),
            "input_file_status": {
                rel.replace("{TICKER}", ticker): bool(files.get(rel.replace("{TICKER}", ticker), "").strip())
                for rel in REQUIRED_FILES + OPTIONAL_FILES
            },
        },
        "memo": memo_info,
        "gics": classification,
        "primers": primers,
        # Legacy field kept so older code paths still resolve; new code reads `gics`/`primers`.
        "sector": {
            "detected": classification["sector"],
            "reason": classification["reason"],
            "primer_path": primers["sector"].get("primer_path", ""),
            "primer_status": primers["sector"].get("primer_status", ""),
        },
        "xbrl_series_present": sorted(xbrl.keys()),
        "chart_specs": chart_specs,
        "claims_count": len(claims),
        "claims": claims,
        "available_inputs": {
            rel.replace("{TICKER}", ticker): str((base / rel.replace("{TICKER}", ticker)).resolve())
            for rel in REQUIRED_FILES + OPTIONAL_FILES
            if (base / rel.replace("{TICKER}", ticker)).exists()
        },
    }

    drafts_dir(base).mkdir(exist_ok=True)
    (drafts_dir(base) / "report_data.json").write_text(
        json.dumps(data, indent=2), encoding="utf-8"
    )
    # Persist the resolved classification for downstream sections / human inspection.
    gics_lines = [f"Sector: {classification['sector']}"]
    if classification.get("industry"):
        gics_lines.append(f"Industry: {classification['industry']}")
    if classification.get("sub_industry"):
        gics_lines.append(f"Sub-Industry: {classification['sub_industry']}")
    gics_lines.append("")
    gics_lines.append(f"Source: {classification['source']}")
    gics_lines.append(f"Note: {classification['reason']}")
    (drafts_dir(base) / "gics_resolved.txt").write_text(
        "\n".join(gics_lines), encoding="utf-8"
    )
    # Legacy file maintained for backward compatibility.
    (drafts_dir(base) / "sector_detected.txt").write_text(
        f"{classification['sector']}\n\n{classification['reason']}\n", encoding="utf-8"
    )

    return data


def print_primer_status(data: dict) -> None:
    """Print prominent, plain-English status of GICS classification and primer presence,
    with the exact prompt-file path to run for any missing primer. Build is never
    blocked by missing primers — the report still produces."""
    gics = data.get("gics", {})
    primers = data.get("primers", {})

    print("")
    print("  --- GICS classification ---")
    print(f"  Sector:       {gics.get('sector', '(none)')}")
    if gics.get("industry"):
        print(f"  Industry:     {gics.get('industry')}")
    if gics.get("sub_industry"):
        print(f"  Sub-Industry: {gics.get('sub_industry')}")
    print(f"  Source:       {gics.get('source', '(unknown)')}")

    print("")
    print("  --- Primer presence (used as enrichment; build is not blocked if missing) ---")
    sec = primers.get("sector", {})
    sec_status = sec.get("primer_status", "")
    if sec_status == "present":
        print(f"  Sector primer:   PRESENT  ({sec.get('primer_path')})")
    elif sec_status == "missing":
        print(f"  Sector primer:   MISSING")
        print(f"    expected at:   {sec.get('primer_path')}")
        if sec.get("research_prompt_path"):
            print(f"    to produce it: run the prompt at {sec.get('research_prompt_path')}")
            print(f"                   on Claude.ai (Research mode); save output at the path above")
        else:
            print(f"    (no research prompt file found for this sector either; consider authoring one)")
    else:
        print(f"  Sector primer:   {sec_status}")

    ind = primers.get("industry", {})
    ind_status = ind.get("primer_status", "")
    if ind_status == "present":
        print(f"  Industry primer: PRESENT  ({ind.get('primer_path')})")
    elif ind_status == "missing":
        print(f"  Industry primer: MISSING")
        print(f"    expected at:   {ind.get('primer_path')}")
        if ind.get("research_prompt_path"):
            print(f"    to produce it: run the prompt at {ind.get('research_prompt_path')}")
            print(f"                   on Claude.ai (Research mode); save output at the path above")
        else:
            print(f"    (no research prompt file found for this industry either; consider authoring one)")
    elif ind_status == "no_industry_classification":
        print(f"  Industry primer: SKIPPED  (no Industry: line in raw/gics.txt — add one to enable)")
    else:
        print(f"  Industry primer: {ind_status}")
    print("")


# ---------- minimal markdown -> HTML (used during assembly) ----------

_INLINE_PATTERNS = [
    (re.compile(r"\*\*(.+?)\*\*"), r"<strong>\1</strong>"),
    (re.compile(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])"), r"<em>\1</em>"),
    (re.compile(r"`([^`]+)`"), r"<code>\1</code>"),
    (re.compile(r"\[([^\]]+)\]\(([^)]+)\)"),
     r'<a href="\2" target="_blank" rel="noopener">\1</a>'),
]

# Inline raw-HTML passthrough. Stashed before html.escape, restored after the
# inline-pattern pass, so the rendered spans appear as styled pills rather
# than as literal angle-bracket text in paragraphs / headers / list items.
_INLINE_PASSTHROUGH_RE = re.compile(
    r'<span\s+[^>]*\bclass\s*=\s*"claim-tag\b[^"]*"[^>]*>.*?</span>',
    re.IGNORECASE | re.DOTALL,
)


def _inline(s: str) -> str:
    stash: list[str] = []

    def _save(m):
        stash.append(m.group(0))
        return f"\x00CLAIMTAG{len(stash) - 1}\x00"

    s = _INLINE_PASSTHROUGH_RE.sub(_save, s)
    s = _html.escape(s)
    for pat, repl in _INLINE_PATTERNS:
        s = pat.sub(repl, s)
    # Restore <a> tags that the inline-link substitution wants to keep.
    s = re.sub(r"&lt;(/?a[^&]*?)&gt;", lambda m: "<" + m.group(1).replace("&quot;", '"') + ">", s)
    # Restore stashed inline raw HTML (claim-tag spans).
    if stash:
        s = re.sub(r"\x00CLAIMTAG(\d+)\x00", lambda m: stash[int(m.group(1))], s)
    return s


RAW_HTML_BLOCK_TAGS = ("aside", "div", "details", "figure", "section", "nav", "header", "footer")


def md_to_html(md: str) -> str:
    """Minimal markdown converter — headers, lists, tables, code, blockquote, hr,
    plus raw-HTML passthrough for block tags listed in RAW_HTML_BLOCK_TAGS."""
    if not md.strip():
        return ""

    lines = md.splitlines()
    out, i = [], 0
    in_code, code_buf = False, []

    def flush_code():
        if code_buf:
            out.append('<pre><code>' + _html.escape("\n".join(code_buf)) + '</code></pre>')
            code_buf.clear()

    while i < len(lines):
        line = lines[i]
        s = line.strip()
        if s.startswith("```"):
            if in_code:
                flush_code(); in_code = False
            else:
                in_code = True
            i += 1; continue
        if in_code:
            code_buf.append(line); i += 1; continue

        # Raw-HTML block passthrough: a line starting with a block-level open tag
        # is accumulated until the matching close tag is seen at depth zero.
        m_open = re.match(r"^\s*<(" + "|".join(RAW_HTML_BLOCK_TAGS) + r")\b", s, re.IGNORECASE)
        if m_open:
            tag = m_open.group(1).lower()
            depth = 0
            buf = []
            open_re = re.compile(rf"<\s*{tag}\b", re.IGNORECASE)
            close_re = re.compile(rf"</\s*{tag}\s*>", re.IGNORECASE)
            while i < len(lines):
                cur = lines[i]
                buf.append(cur)
                depth += len(open_re.findall(cur))
                depth -= len(close_re.findall(cur))
                i += 1
                if depth <= 0:
                    break
            out.append("\n".join(buf))
            continue

        m = re.match(r"^(#{1,6})\s+(.+)$", s)
        if m:
            lvl = len(m.group(1))
            out.append(f"<h{lvl}>{_inline(m.group(2))}</h{lvl}>")
            i += 1; continue
        if re.match(r"^-{3,}$", s) or re.match(r"^\*{3,}$", s):
            out.append("<hr/>"); i += 1; continue
        if "|" in s and i + 1 < len(lines) and re.match(r"^\s*\|?\s*[-:|\s]+\s*\|?\s*$", lines[i + 1]):
            tbl = [s]; sep = lines[i + 1]; i += 2
            while i < len(lines) and "|" in lines[i] and lines[i].strip():
                tbl.append(lines[i].strip()); i += 1
            out.append(_render_table(tbl, sep)); continue
        if s.startswith(">"):
            qbuf = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                qbuf.append(lines[i].strip().lstrip(">").lstrip())
                i += 1
            out.append("<blockquote>" + _inline(" ".join(qbuf)) + "</blockquote>")
            continue
        if re.match(r"^\s*[-*+]\s+", line):
            items = []
            while i < len(lines) and re.match(r"^\s*[-*+]\s+", lines[i]):
                items.append(_inline(re.sub(r"^\s*[-*+]\s+", "", lines[i])))
                i += 1
            out.append("<ul>" + "".join(f"<li>{x}</li>" for x in items) + "</ul>")
            continue
        if re.match(r"^\s*\d+\.\s+", line):
            items = []
            while i < len(lines) and re.match(r"^\s*\d+\.\s+", lines[i]):
                items.append(_inline(re.sub(r"^\s*\d+\.\s+", "", lines[i])))
                i += 1
            out.append("<ol>" + "".join(f"<li>{x}</li>" for x in items) + "</ol>")
            continue
        if s:
            pbuf = [s]; i += 1
            while i < len(lines) and lines[i].strip() and not _para_break(lines[i]):
                pbuf.append(lines[i].strip()); i += 1
            out.append("<p>" + _inline(" ".join(pbuf)) + "</p>")
            continue
        i += 1

    flush_code()
    return "\n".join(out)


def _para_break(line: str) -> bool:
    s = line.strip()
    if not s: return True
    return any([
        s.startswith("#"),
        s.startswith("```"),
        s.startswith(">"),
        bool(re.match(r"^\s*[-*+]\s+", line)),
        bool(re.match(r"^\s*\d+\.\s+", line)),
        bool(re.match(r"^-{3,}$", s)),
        bool(re.match(r"^\*{3,}$", s)),
    ])


def _render_table(lines, sep):
    def split_row(r):
        r = r.strip()
        if r.startswith("|"): r = r[1:]
        if r.endswith("|"): r = r[:-1]
        return [c.strip() for c in r.split("|")]
    headers = split_row(lines[0])
    rows = [split_row(l) for l in lines[1:]]
    out = ['<table><thead><tr>']
    for h in headers:
        out.append(f"<th>{_inline(h)}</th>")
    out.append('</tr></thead><tbody>')
    for r in rows:
        out.append("<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in r) + "</tr>")
    out.append('</tbody></table>')
    return "".join(out)


# ---------- assemble phase ----------

def assemble(base: Path, ticker: str) -> Path:
    """Read drafts + report_data.json, run glossary inject, build HTML."""
    data_path = drafts_dir(base) / "report_data.json"
    if not data_path.exists():
        print("ERROR: report_data.json missing — run with --prep first.", file=sys.stderr)
        sys.exit(1)
    data = json.loads(data_path.read_text(encoding="utf-8"))

    section_html: list[str] = []
    missing_drafts: list[str] = []

    # Pre-render charts once (used by section 4 by default; could be re-routed
    # later via the caption_slot_section field).
    chart_html_by_id: dict[str, str] = {
        spec["id"]: render_chart(spec) for spec in data.get("chart_specs", [])
    }

    sector = data.get("sector", {}).get("detected") or None
    company_glossary_path = drafts_dir(base) / "glossary_company.json"

    for num, slug, title, kind in SECTIONS:
        anchor_id = f"section-{num:02d}-{slug}"
        if kind == "claude":
            p = section_path(base, num, slug)
            if not p.exists():
                missing_drafts.append(f"{num:02d}-{slug}")
                section_html.append(_missing_section_html(num, slug, title, anchor_id))
                continue
            md = p.read_text(encoding="utf-8")
            inner = md_to_html(md)
            if HAS_GLOSSARY_INJECT:
                inner = inject_glossary.inject(
                    inner,
                    scope_id=anchor_id,
                    sector=sector,
                    company_glossary_path=company_glossary_path,
                )
            # Drop in chart pack if this section is the caption slot for any chart.
            charts_for_section = [
                chart_html_by_id[s["id"]]
                for s in data.get("chart_specs", [])
                if s.get("caption_slot_section") == num and s["id"] in chart_html_by_id
            ]
            charts_block = ""
            if charts_for_section:
                charts_block = (
                    '<div class="charts-grid">'
                    + "".join(charts_for_section)
                    + "</div>"
                )
            section_html.append(
                f'<section id="{anchor_id}" class="report-section">'
                f'<h2>{num}. {_html.escape(title)}</h2>'
                f'{charts_block}'
                f'{inner}'
                f'</section>'
            )
        elif kind == "auto":
            section_html.append(_auto_section_html(num, slug, title, anchor_id, base, ticker, data))

    template_path = SKILL_DIR / "templates" / "report.html"
    if template_path.exists():
        template = template_path.read_text(encoding="utf-8")
        body_html = "".join(section_html)
        toc_html = _build_toc()
        cover_html = _build_cover(data, ticker)
        rendered = (
            template
            .replace("{{COVER}}", cover_html)
            .replace("{{TOC}}", toc_html)
            .replace("{{BODY}}", body_html)
            .replace("{{COMPANY}}", _html.escape(data["memo"].get("company") or ticker))
            .replace("{{TICKER}}", _html.escape(ticker))
        )
    else:
        rendered = _fallback_html(ticker, data, section_html)

    out_path = base / f"{ticker}_full_report.html"
    out_path.write_text(rendered, encoding="utf-8")

    print(f"Built report: {out_path}")
    print(f"  size: {len(rendered):,} bytes")
    print(f"  charts: {len(data.get('chart_specs', []))}")
    print(f"  decision: {data['memo'].get('decision') or '(not parsed)'}")
    print(f"  current price: {data['memo'].get('current_price') or '(not parsed)'}")
    print(f"  sector: {data['sector']['detected']}")
    if missing_drafts:
        print(f"  WARNING: {len(missing_drafts)} sections missing drafts: {', '.join(missing_drafts)}",
              file=sys.stderr)
    if not HAS_GLOSSARY_INJECT:
        print("  NOTE: inject_glossary not yet implemented - glossary spans not added.",
              file=sys.stderr)
    if not template_path.exists():
        print("  NOTE: templates/report.html not yet implemented - using fallback skin.",
              file=sys.stderr)

    return out_path


def _missing_section_html(num: int, slug: str, title: str, anchor_id: str) -> str:
    return (
        f'<section id="{anchor_id}" class="report-section missing-draft">'
        f'<h2>{num}. {_html.escape(title)}</h2>'
        f'<div class="callout warning">'
        f'<strong>Section draft not yet written.</strong> '
        f'Claude must produce <code>{section_filename(num, slug)}</code> per the '
        f'per-section writing prompt in <code>SKILL.md</code> before this section can render.'
        f'</div></section>'
    )


def _strip_analyst_metadata(md: str) -> str:
    """Remove analyst-internal markers from text sourced from working files.
    Used in auto-generated sections that paste from verification / bug files."""
    md = re.sub(r"\[Step\s+\d+(?:\.\d+)?\]\s*", "", md)
    md = re.sub(r"===+", "", md)
    md = re.sub(r"\[(FACT|INTERPRETATION|HUMAN-VERIFY|GAP)\s*\|[^\]]*\]", "", md)
    md = re.sub(r"^Step\s+\d+\b[^\n]*\n", "", md, flags=re.MULTILINE)
    md = re.sub(r"^(Inputs|Sources|Scope|Date of analysis|Prompt-injection)\s*:[^\n]*\n",
                "", md, flags=re.MULTILINE | re.IGNORECASE)
    return md


def _auto_section_html(num: int, slug: str, title: str, anchor_id: str,
                       base: Path, ticker: str, data: dict) -> str:
    if slug == "reliability":
        ver_a = read_text(base / "raw" / "verification_a.md")
        ver_c = read_text(base / "steps" / "verification_c.md")
        ccatches = read_text(base / "raw" / "cc_catches_against_codex.md")
        bugs_cc = read_text(base / "bugs_encountered.md")
        bugs_codex = read_text(base / "bugs_encountered_codex.md")
        body = ""
        if ver_c.strip():
            body += "<h3>Verification C (final pre-memo gate)</h3>" + md_to_html(_strip_analyst_metadata(ver_c))
        elif ver_a.strip():
            body += "<h3>Verification A (initial pass)</h3>" + md_to_html(_strip_analyst_metadata(ver_a))
        if ccatches.strip():
            body += "<h3>Cross-model audit (CC catches against Codex)</h3>" + md_to_html(_strip_analyst_metadata(ccatches))
        if bugs_cc.strip():
            body += "<details><summary>CC-side bug log</summary>" + md_to_html(_strip_analyst_metadata(bugs_cc)) + "</details>"
        if bugs_codex.strip():
            body += "<details><summary>Codex-side bug log</summary>" + md_to_html(_strip_analyst_metadata(bugs_codex)) + "</details>"
        return (f'<section id="{anchor_id}" class="report-section">'
                f'<h2>{num}. {_html.escape(title)}</h2>{body}</section>')
    if slug == "glossary":
        body = (
            "<p>Hover-tooltip glossary terms appear inline throughout the report. "
            "Expanded definitions live in the core finance glossary "
            f"(<code>{(SKILL_DIR / 'assets' / 'glossary_core.json').relative_to(SKILL_DIR)}</code>) "
            "and the sector primer.</p>"
        )
        return (f'<section id="{anchor_id}" class="report-section">'
                f'<h2>{num}. {_html.escape(title)}</h2>{body}</section>')
    if slug == "sources":
        items = []
        for rel, abspath in data["available_inputs"].items():
            items.append(f"<li><code>{_html.escape(rel)}</code></li>")
        body = "<p>Inputs read by this report:</p><ul>" + "".join(items) + "</ul>"
        return (f'<section id="{anchor_id}" class="report-section">'
                f'<h2>{num}. {_html.escape(title)}</h2>{body}</section>')
    return f'<section id="{anchor_id}" class="report-section"><h2>{num}. {_html.escape(title)}</h2></section>'


def _build_toc() -> str:
    items = "".join(
        f'<li><a href="#section-{num:02d}-{slug}">{num}. {_html.escape(title)}</a></li>'
        for num, slug, title, _ in SECTIONS
    )
    return f'<nav class="toc"><strong>Sections</strong><ol>{items}</ol></nav>'


def _build_cover(data: dict, ticker: str) -> str:
    memo = data["memo"]
    company = _html.escape(memo.get("company") or ticker)
    decision = memo.get("decision") or "DECISION NOT PARSED"
    decision_class = decision.lower()
    price = _html.escape(memo.get("current_price") or "—")
    today = _dt.date.today().isoformat()
    return (
        f'<header class="cover">'
        f'<h1>{company}</h1>'
        f'<div class="ticker">{_html.escape(ticker)} · Built {today}</div>'
        f'<div><span class="verdict-banner {decision_class}">{_html.escape(decision)}</span></div>'
        f'<p class="thesis">Current price {price}</p>'
        f'</header>'
    )


# ---------- fallback HTML (used when templates/report.html absent) ----------

_FALLBACK_CSS = """
body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
       line-height: 1.55; color: #1a1a1a; max-width: 940px;
       margin: 0 auto; padding: 32px 28px 80px; background: #fff; }
header.cover { border-bottom: 3px solid #1a1a1a; padding-bottom: 18px; margin-bottom: 28px; }
.cover h1 { margin: 0 0 6px; font-size: 28px; }
.cover .ticker { font-size: 16px; color: #666; }
.verdict-banner { display: inline-block; padding: 8px 16px; border-radius: 4px;
                  font-weight: 600; letter-spacing: 0.04em; text-transform: uppercase;
                  margin: 14px 0 6px; font-size: 14px; }
.verdict-banner.buy { background: #2ca02c; color: #fff; }
.verdict-banner.watchlist { background: #ff7f0e; color: #fff; }
.verdict-banner.pass { background: #d62728; color: #fff; }
.verdict-banner.reject { background: #d62728; color: #fff; }
nav.toc { background: #f7f7f7; padding: 14px 18px; border-radius: 6px;
          margin-bottom: 32px; font-size: 14px; }
nav.toc ol { margin: 0; padding-left: 20px; }
nav.toc a { color: #1f77b4; text-decoration: none; }
section.report-section { margin: 36px 0; padding-top: 12px;
                          border-top: 1px solid #e6e6e6; }
section.report-section > h2 { font-size: 22px; margin: 0 0 4px; }
section.missing-draft { opacity: 0.6; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 13px; }
th, td { border: 1px solid #ddd; padding: 6px 9px; text-align: left; vertical-align: top; }
th { background: #f3f3f3; font-weight: 600; }
tr:nth-child(even) td { background: #fafafa; }
.callout { background: #f7f9fb; border-left: 4px solid #1f77b4;
           padding: 14px 18px; margin: 18px 0; border-radius: 0 4px 4px 0; }
.callout.warning { border-left-color: #d62728; background: #fdf3f3; }
.charts-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; margin: 16px 0; }
"""


def _fallback_html(ticker: str, data: dict, section_html: list[str]) -> str:
    cover = _build_cover(data, ticker)
    toc = _build_toc()
    company = _html.escape(data["memo"].get("company") or ticker)
    return (
        f'<!doctype html><html lang="en"><head><meta charset="utf-8">'
        f'<meta name="viewport" content="width=device-width, initial-scale=1">'
        f'<title>{company} — Investment Report</title>'
        f'<style>{_FALLBACK_CSS}</style></head>'
        f'<body>{cover}{toc}{"".join(section_html)}'
        f'<footer style="margin-top:60px;padding-top:18px;border-top:1px solid #e6e6e6;'
        f'font-size:12px;color:#888;">Built by /stock-report (fallback skin; '
        f'templates/report.html not yet present).</footer></body></html>'
    )


# ---------- main ----------

def main():
    parser = argparse.ArgumentParser(description="Build /stock-report HTML from a research folder.")
    parser.add_argument("ticker")
    parser.add_argument("--base", default=None, help="Override base directory")
    parser.add_argument("--prep", action="store_true", help="Run prep phase only")
    parser.add_argument("--assemble", action="store_true", help="Run assemble phase only")
    parser.add_argument("--rebuild", action="store_true", help="Clear all section drafts before running")
    parser.add_argument("--rebuild-section", type=int, metavar="N",
                        help="Clear one section's draft before running")
    parser.add_argument("--status", action="store_true", help="Show per-section draft status and exit")
    args = parser.parse_args()

    ticker = args.ticker.upper()
    base = Path(args.base) if args.base else Path(f"~/Research/{ticker}")
    base = base.resolve()
    if not base.exists():
        print(f"ERROR: base directory not found: {base}", file=sys.stderr)
        sys.exit(1)

    if args.status:
        statuses = check_drafts(base)
        for s in statuses:
            tag = s["status"].ljust(8)
            extra = f" ({s['words']}w)" if s.get("words") else ""
            print(f"  {s['num']:02d} {tag} {s['title']}{extra}")
        return

    if args.rebuild and args.rebuild_section:
        print("ERROR: --rebuild and --rebuild-section are mutually exclusive.", file=sys.stderr)
        sys.exit(2)
    if args.rebuild:
        deleted = clear_drafts(base)
        print(f"Cleared {len(deleted)} draft(s): {', '.join(deleted) or '(none)'}")
    elif args.rebuild_section:
        deleted = clear_drafts(base, only_section=args.rebuild_section)
        print(f"Cleared section {args.rebuild_section}: {', '.join(deleted) or '(no draft existed)'}")

    do_prep = args.prep or not args.assemble
    do_assemble = args.assemble or not args.prep
    if not (args.prep or args.assemble):
        do_prep = do_assemble = True

    if do_prep:
        print(f"Prep phase for {ticker}...")
        data = prep(base, ticker)
        print_primer_status(data)
        print(f"  XBRL series: {len(data['xbrl_series_present'])}")
        print(f"  Claims indexed: {data['claims_count']}")
        print(f"  report_data.json written to {drafts_dir(base) / 'report_data.json'}")
        statuses = check_drafts(base)
        missing = [s for s in statuses if s["status"] == "missing"]
        if missing:
            missing_list = ", ".join(f"{s['num']:02d}-{s['slug']}" for s in missing)
            print(f"  {len(missing)} section drafts still pending: {missing_list}")

    if do_assemble:
        print(f"Assemble phase for {ticker}...")
        assemble(base, ticker)


if __name__ == "__main__":
    main()
